const API_BASE=localStorage.getItem('LUDO_MASTER_API')||'https://YOUR-RENDER-SERVICE.onrender.com';
let socket=null,currentMatch=null,adminKey=sessionStorage.getItem('LUDO_ADMIN_KEY')||'';
const ENTRIES=[50,30,60],WINS=[90,50,110];
function savePage(p){try{localStorage.setItem('LUDO_MASTER_PAGE',p)}catch(e){}}
function show(page){savePage(page);const c=document.getElementById('content');
if(page==='home')c.innerHTML=`<div class="card" style="text-align:center;padding:28px 18px"><h2>🎲 Ludo Master-এ সবাইকে স্বাগতম 🥰</h2><p>খেলুন, ম্যাচে অংশ নিন এবং Wallet পরিচালনা করুন।</p></div><div class="card"><button class="action" onclick="show('matches')">🎮 Matches দেখুন</button></div>`;
if(page==='matches'){c.innerHTML=`<div class="card"><h2>🎮 Matches</h2><p class="small">Real-time 2 Player Match</p><p id="backendStatus" class="small">Connecting...</p></div>`+ENTRIES.map((e,i)=>`<div class="card"><h3>1 vs 1 — Match ${i+1}</h3><p><b>Entry Fee:</b> ৳${e}</p><p><b>Winning:</b> ৳${WINS[i]}</p><p id="m${i}" class="small">Loading...</p><button class="action yellow" onclick="joinMatch(${e},${WINS[i]})">Join</button></div>`).join('');loadMatches();}
if(page==='tournament')c.innerHTML='<div class="card"><h2>🏆 Tournament</h2><p>Coming soon</p></div>';
if(page==='wallet')renderWallet();
if(page==='profile'){const n=localStorage.getItem('LUDO_MASTER_NAME')||'';c.innerHTML=`<div class="card"><h2>👤 Profile</h2><input id="playerName" class="input" value="${escapeHtml(n)}" placeholder="আপনার নাম"><button class="action" onclick="saveName()">Save</button></div>`;}
if(page==='admin')renderAdmin();}
function renderWallet(){const c=document.getElementById('content');c.innerHTML=`<div class="card"><h2>💰 Wallet</h2><div class="balance">৳0.00</div><p class="small">Current balance</p></div><div class="card"><h3>Deposit</h3><div class="payment-methods"><div class="pay-card" onclick="showPaymentNumber('bkash')"><img src="https://cdn.imgbin.com/6/21/13/bkash-logo-bkash-mobile-payment-service-logo-T5Fr3NvD.jpg"><b>bKash</b></div><div class="pay-card" onclick="showPaymentNumber('nagad')"><img src="https://download.logo.wine/logo/Nagad/Nagad-Logo.wine.png"><b>Nagad</b></div></div><div id="payment-number-box" class="payment-number-box" style="display:none"><div id="payment-service"></div><div id="payment-number">01301470686</div><button onclick="copyPaymentNumber()">Copy Number</button></div><label><b>Payment Method</b></label><select id="payMethod" class="input"><option>bKash</option><option>Nagad</option></select><label style="display:block;margin-top:12px"><b>Deposit Amount (৳)</b></label><input id="depositAmount" class="input" type="number" min="1" placeholder="যেমন: 100"><label style="display:block;margin-top:12px"><b>Transaction ID</b></label><input id="trxId" class="input" placeholder="Transaction ID লিখুন"><label style="display:block;margin-top:12px"><b>Payment Screenshot / Proof</b></label><input id="proof" class="input" type="file" accept="image/*"><button class="action" onclick="submitDeposit()">Submit Deposit</button><p class="small">Transaction ID ও screenshot দিয়ে Submit করুন। Admin যাচাই করার পর balance যোগ হবে।</p></div>`;}
function showPaymentNumber(type){document.getElementById('payment-number-box').style.display='block';document.getElementById('payment-service').textContent=type==='bkash'?'bKash Number':'Nagad Number';document.getElementById('payment-number').textContent='01301470686';}
function copyPaymentNumber(){navigator.clipboard?.writeText('01301470686').then(()=>alert('Number copied: 01301470686'),()=>alert('Number: 01301470686'));}
function submitDeposit(){const method=document.getElementById('payMethod').value,amount=document.getElementById('depositAmount').value,trx=document.getElementById('trxId').value.trim(),proof=document.getElementById('proof').files[0];if(!amount||Number(amount)<=0)return alert('Deposit amount লিখুন');if(!trx)return alert('Transaction ID লিখুন');if(!proof)return alert('Payment screenshot upload করুন');const old=JSON.parse(localStorage.getItem('depositRequests')||'[]');old.push({method,amount:Number(amount),trxId:trx,proofName:proof.name,status:'Pending',time:new Date().toLocaleString()});localStorage.setItem('depositRequests',JSON.stringify(old));alert('Deposit request submitted! Pending থাকবে।');show('wallet');}
function saveName(){localStorage.setItem('LUDO_MASTER_NAME',document.getElementById('playerName').value.trim()||'Player');alert('Name saved');}
async function api(path,opts={}){const r=await fetch(API_BASE+path,opts);if(!r.ok){let msg='Request failed';try{const x=await r.json();msg=x.error||msg}catch(e){}throw new Error(msg)}return r.json();}
async function loadMatches(){try{const data=await api('/api/matches');document.getElementById('backendStatus').textContent='🟢 Real-time backend connected';for(let i=0;i<3;i++){const m=data.find(x=>x.entry===ENTRIES[i]);const el=document.getElementById('m'+i);if(el)el.textContent=m?`${m.players.length}/2 Players${m.roomCode?' • Room Code ready':''}`:'0/2 Players — Ready to join';}}catch(e){const s=document.getElementById('backendStatus');if(s)s.textContent='🔴 Backend URL সেট করা হয়নি';document.querySelectorAll('[id^=m]').forEach(x=>x.textContent='Backend connect হলে player count দেখাবে');}}
async function joinMatch(entry,winning){const name=localStorage.getItem('LUDO_MASTER_NAME')||prompt('আপনার নাম লিখুন')||'Player';localStorage.setItem('LUDO_MASTER_NAME',name);try{let data=await api('/api/matches');let m=data.find(x=>x.entry===entry&&x.winning===winning&&x.players.length<2&&x.status==='waiting');if(!m)m=await api('/api/matches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entry,winning})});currentMatch=m;connect(m.matchId,name);}catch(e){alert('Backend connection হয়নি: '+e.message);}}
function connect(matchId,name){if(socket)socket.disconnect();socket=io(API_BASE);socket.on('connect',()=>socket.emit('match:join',{matchId,name}));socket.on('match:update',renderMatch);socket.on('match:error',x=>alert(x.message||x));}
function renderMatch(m){currentMatch=m;const c=document.getElementById('content');c.innerHTML=`<div class="card"><h2>🎮 Match ৳${m.entry}</h2><p><b>Players:</b> ${m.players.length}/2</p>${m.players.map(p=>`<p>👤 ${escapeHtml(p.name)}</p>`).join('')}${m.players.length===2?'<p class="ok">✅ Match Full — Admin Start করতে পারবে</p>':'<p class="warn">⏳ 2 জন Player-এর অপেক্ষা চলছে</p>'}${m.roomCode?`<div class="payment-number-box"><b>Ludo King Room Code</b><div id="roomCode" class="room">${escapeHtml(m.roomCode)}</div><button onclick="copyCode()">Copy Code</button></div>`:'<div class="payment-number-box"><b>Ludo King Room Code</b><p class="small">Code এখনো ফাঁকা। Admin Ludo King থেকে আসল code বসিয়ে Publish করলে এখানে আসবে।</p></div>'}</div><button class="action" onclick="show('matches')">← Matches</button>`;}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function copyCode(){const x=document.getElementById('roomCode')?.textContent||'';navigator.clipboard?.writeText(x).then(()=>alert('Code copied: '+x));}
async function renderAdmin(){const c=document.getElementById('content');if(!adminKey){c.innerHTML='<div class="card"><h2>🔐 Admin Login</h2><p class="small">Render-এর ADMIN_KEY দিন।</p><input id="adminKey" type="password" class="input" placeholder="Admin Key"><button class="action" onclick="loginAdmin()">Login</button></div>';return;}try{const data=await api('/api/matches');c.innerHTML='<div class="card"><h2>🔐 Admin Panel</h2><p class="small">2/2 হলে Start করুন। তারপর Ludo King-এর আসল Room Code লিখে Publish করুন।</p><button class="action" onclick="adminLogout()">Logout</button></div>'+ENTRIES.map((e,i)=>{const m=data.find(x=>x.entry===e);return `<div class="card"><h3>Match ${i+1} — ৳${e} → ৳${WINS[i]}</h3><p><b>Players:</b> ${m?m.players.length:0}/2</p><p><b>Room Code:</b> ${m&&m.roomCode?escapeHtml(m.roomCode):'ফাঁকা'}</p>${m?`<button class="action" ${m.players.length!==2?'disabled':''} onclick="adminStart('${m.matchId}')">${m.players.length===2?'▶ Start & Room Code':'⏳ 2 Players হলে Start'}</button>`:'<p class="small">কোনো active match নেই</p>'}</div>`}).join('');}catch(e){adminKey='';sessionStorage.removeItem('LUDO_ADMIN_KEY');c.innerHTML='<div class="card"><p>Admin authentication failed.</p></div>';}}
function loginAdmin(){const v=document.getElementById('adminKey').value.trim();if(!v)return alert('Admin Key দিন');adminKey=v;sessionStorage.setItem('LUDO_ADMIN_KEY',v);renderAdmin();}
function adminLogout(){adminKey='';sessionStorage.removeItem('LUDO_ADMIN_KEY');renderAdmin();}
async function adminStart(matchId){try{const data=await api('/api/matches');const m=data.find(x=>x.matchId===matchId);if(!m||m.players.length!==2)return alert('2 জন player join না করলে Start করা যাবে না।');const code=prompt('Ludo King-এ room তৈরি করে আসল Room Code লিখুন।\nCode এখনো প্রকাশ হবে না যতক্ষণ Publish না করেন:','');if(code===null)return;if(!code.trim())return alert('Room Code ফাঁকা রাখা হয়েছে।');await api('/api/matches/'+encodeURIComponent(matchId)+'/room',{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':adminKey},body:JSON.stringify({roomCode:code.trim()})});alert('Room Code players-দের কাছে প্রকাশ হয়েছে।');renderAdmin();}catch(e){if(/401|403|admin/i.test(e.message)){adminKey='';sessionStorage.removeItem('LUDO_ADMIN_KEY');}alert(e.message||'Publish failed');renderAdmin();}}
show(localStorage.getItem('LUDO_MASTER_PAGE')||'home');
